### ISSUE TITLE
tusimple benchmark ground truth

### ISSUE THREAD

**Issue by kivinju** [TuSimple/tusimple-benchmark#3]
https://www.kaggle.com/datasets/manideep1108/tusimple?resource=download 

The links below do not work anymore. Please use the Kaggle link above to download the dataset.
---

# LANE DETECTION CHALLENGE
## dataset
- [train_set.zip](https://s3.us-east-2.amazonaws.com/benchmark-frontend/datasets/1/train_set.zip)
- [test_set.zip](https://s3.us-east-2.amazonaws.com/benchmark-frontend/datasets/1/test_set.zip)
- [test_baseline.json](https://s3.us-east-2.amazonaws.com/benchmark-frontend/datasets/1/test_baseline.json)
## ground truth
- [test_label.json](https://s3.us-east-2.amazonaws.com/benchmark-frontend/truth/1/test_label.json)
# VELOCITY ESTIMATION CHALLENGE
## dataset
- [benchmark_velocity_train.zip](https://s3.us-east-2.amazonaws.com/benchmark-frontend/datasets/2/benchmark_velocity_train.zip)
- [benchmark_velocity_test.zip](https://s3.us-east-2.amazonaws.com/benchmark-frontend/datasets/2/benchmark_velocity_test.zip)
- [benchmark_velocity_supp.zip](https://s3.us-east-2.amazonaws.com/benchmark-frontend/datasets/2/benchmark_velocity_supp.zip)
- [baseline.json](https://s3.us-east-2.amazonaws.com/benchmark-frontend/datasets/2/baseline.json)
## ground trurh
- [gt.json](https://s3.us-east-2.amazonaws.com/benchmark-frontend/truth/2/gt.json)

**Comment by cardwing** [comment]
@kivinju , thanks for uploading the ground-truth labels.

**Comment by cardwing** [comment]
@kivinju , really appreciate your kind response.

**Comment by wcg5262** [comment]
@kivinju 您好，如果我想自己制作此类数据集，也要做您提供的这种json文件，我要从何入手呢？

**Comment by kivinju** [comment]
> @kivinju 您好，如果我想自己制作此类数据集，也要做您提供的这种json文件，我要从何入手呢？

format your output and document.

**Comment by harryhan618** [comment]
Hi, thanks for sharing. May I ask what's the method used in baseline for lane detection?

**Comment by fabvio** [comment]
Hi, thanks for releasing the dataset. Just to let you know, I provide class labels for the lane boundaries in the training and validation set. Maybe someone is interested.

https://github.com/fabvio/TuSimple-lane-classes

**Comment by jiaofang1222** [comment]
> @kivinju 您好，如果我想自己制作此类数据集，也要做您提供的这种json文件，我要从何入手呢？

您好，能分享一下生成.json文件的程序吗？

**Comment by noobliang** [comment]
Hi, this file .json can be open directly by browser ，should i copy all to a json file ??  i am a newman ,i dont know how to use it ,  thanks a million..!

**Comment by obulirajs** [comment]
> Hi, thanks for releasing the dataset. Just to let you know, I provide class labels for the lane boundaries in the training and validation set. Maybe someone is interested.
> 
> https://github.com/fabvio/TuSimple-lane-classes

As part of my academics i chose to do project on lane detection. I need to do labeling on the road lanes as part of my project work. i am pretty new to this domain and i do not know how to do. Can you help me in pointing right tool to do labeling and how to do. Any help is much appreciated.

-Thanks 
Raj

**Comment by fabvio** [comment]
Well I just wrote my own labeling tool for this specific dataset using python :) if you need it please open an issue on my repo, side things like this shouldn't be discussed here.

**Comment by DGJSCUT** [comment]
Is there any possibility that the author could share the code or method of the dataset TuSimple about how to label it in a json format with us?

**Comment by Aya-S** [comment]
I would like to download only a small subset of the dataset and advice on how to do that?

**Comment by pandamax** [comment]
if i have lane instance segmentation images，is there a method to generate json format like Tusimple?thans in advance.

**Comment by mohamadalii** [comment]
Hello, I would like to test Lane detection on real-time camera without the dataset, could anyone help me?

**Comment by eeyrw** [comment]
I wrote some simple code for walking through tusimple dataset and other popular datasets:
https://github.com/eeyrw/LaneDatasetInspector

**Comment by HejhGitHub** [comment]
Hello ，I am a college student just getting started, may I just want to do lane detection research. Do I still need to look at the data set of VELOCITY ESTIMATION CHALLENGE? Or where is this part of the data set used? Looking forward to your reply。thank you

**Comment by ntthuy11** [comment]
Hi TuSimple engineers, is it possible that you can share your annotation tool for lanes? I would like to train bike lanes by myself, and I am searching around for a good tool for lanes. I will follow TuSimple license. Thank you very much in advance!

**Comment by jinlang226** [comment]
Hi, what does **240 and 710** mean in the JSON file? Do those two numbers have specific meaning? Thanks!

横坐标[-2, -2, -2, -2, 632, 625, 617, 609, 601, 594, 586, 578, 570, 563, 555, 547, 539, 532, 524, 516, 508, 501, 493, 485, 477, 469, 462, 454, 446, 438, 431, 423, 415, 407, 400, 392, 384, 376, 369, 361, 353, 345, 338, 330, 322, 314, 307, 299], 
纵坐标[**240**, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700, **710**]

**Comment by HejhGitHub** [comment]
您好 请问为什么test_baseline.json和test_label.json点进去不是直接下载呢

**Comment by HejhGitHub** [comment]
您好· 请问我测试tusimple数据集时Traceback (most recent call last):
  File "test_tusimple.py", line 141, in <module>
    os.path.join(Dataset_Path['Tusimple'], 'test_label.json'))
  File "D:\download_code\SCNN_Pytorch-master\utils\lane_evaluation\tusimple\lane.py", line 73, in bench_one_submit
    raise Exception('Some raw_file from your predictions do not exist in the test tasks.')
Exception: Some raw_file from your predictions do not exist in the test tasks.是哪里出了问题

**Comment by ooguz166** [comment]
Hello everyone is there any code that I can use it as a baseline for anchorpoint extraction from the predicted lane maps for comparison ? Thank you very much in advance!

**Comment by Siddharth-Prajapatii** [comment]
Hello
I would like to know the license of the dataset? Is it possible to use TuSimple dataset for commercial purposes?
Thank You

**Comment by kivinju** [comment]
Hi,

Thanks for asking. I am consulting our legal team for the license.

Kai

*Kai Zhou*
Service Infra Manager
------------------------------
------------------------------


*MWA*
+1(619)916-3144
www.tusimple.com
9191 Towne Centre Dr, Ste 600, San Diego, CA 92122

**Comment by CuiJiandong1230** [comment]
Hello,  can somebody help me to find this 4 json files? I unzipped all the zip files but I couldn't find them.
I will really appreciate your help.
$TUSIMPLEROOT/lable_data_xxxx.json # label json file x4

**Comment by fangxiao-dev** [comment]
@kivinju Isn't it *Apache 2.0* license, as posted on the homepage of this repository?

**Comment by kivinju** [comment]
@dexter2406 Yes. I confirmed with our legal team and made it Apache 2.0.

**Comment by Frandre** [comment]
Thanks for sharing the dataset!

Could you please advice whether camera parameters, e.g. intrinsic, are available for your dataset or not?

Best,
Buyu

**Comment by wywywy01** [comment]
Thanks for your sharing.

It seems that in 'LANE DETECTION CHALLENGE', the data  test_label.json line is 2782, while in test_set.zip only exists 2638 imgs.

could you please have a check?

**Comment by Takugo** [comment]
> if i have lane instance segmentation images，is there a method to generate json format like Tusimple?thanks in advance.

Hi, have you found any tools or scripts that could generate TuSimple json format from lane instance segmentation images. I also have this sort of problems.

**Comment by miao02830** [comment]
> > 如果我有车道实例分割图像，有没有办法生成像 Tusimple 这样的 json 格式？提前谢谢。
> 
> 嗨，您是否找到了可以从车道实例分割图像生成 TuSimple json 格式的任何工具或脚本。我也有这样的问题。

同问，我也遇到了这样的问题，可以分享一下吗，十分感谢

**Comment by pandamax** [comment]
@miao02830  我这边实现了车道线实例分割数据集转tusimple的脚本，可能你的数据集标注形式类似于vil-100或curvelanes，可以参考一下[vil-100转tusimple](https://blog.csdn.net/pandamax/article/details/119926552?spm=1001.2014.3001.5501)、[curvelanes转tusimple](https://blog.csdn.net/pandamax/article/details/119924240?spm=1001.2014.3001.5501)

reference:
- [convert vil-100 to tusimple](https://github.com/pandamax/parse_vil100)
- [convert CurveLanes to tusimple](https://github.com/pandamax/Parse_Curvelanes)

**Comment by Takugo** [comment]
> @miao02830 我这边实现了车道线实例分割数据集转tusimple的脚本，可能你的数据集标注形式类似于vil-100或curvelanes，可以参考一下[vil-100转tusimple](https://blog.csdn.net/pandamax/article/details/119926552?spm=1001.2014.3001.5501)、[curvelanes转tusimple](https://blog.csdn.net/pandamax/article/details/119924240?spm=1001.2014.3001.5501)
> 
> reference:
> 
> * [convert vil-100 to tusimple](https://github.com/pandamax/parse_vil100)
> * [convert CurveLanes to tusimple](https://github.com/pandamax/Parse_Curvelanes)

@pandamax 嗯？环宇？

**Comment by harinduravin** [comment]
> Hi, thanks for releasing the dataset. Just to let you know, I provide class labels for the lane boundaries in the training and validation set. Maybe someone is interested.
> 
> https://github.com/fabvio/TuSimple-lane-classes

Do you have labeled data for TuSimple Test set (test_label.json) as well? @fabvio
If possible, please share.

**Comment by zillur01** [comment]
Does this dataset have lane class labels? Like dashed yellow = 1, sold yellow = 2, bot dotts = 3 or they are all considered as one class? I do not see any labels on the json files.

**Comment by josh-wende** [comment]
These links don't work for me, I get an "Access Denied" message. Is there somewhere else I can get the dataset?

**Comment by zehranrgi** [comment]
> These links don't work for me, I get an "Access Denied" message. Is there somewhere else I can get the dataset?

https://www.kaggle.com/datasets/manideep1108/tusimple?resource=download

**Comment by SANGHEEMOON** [comment]
Hello,
I can't find 'test_baseline.json'. How can I get this file?

**Comment by 02666** [comment]
How could i download these datasets?

**Comment by wy1663890176** [comment]
数据集下载不了，还有其他的方法获取数据吗

**Comment by lsj1012** [comment]
The dataset can't be downloaded, can you reply to it?

**Comment by kivinju** [comment]
Hi @lsj1012 @wy1663890176 @02666 @SANGHEEMOON I am no longer with TuSimple and it seems that the company has disable the links. Please use the Kaggle link to download the dataset: https://www.kaggle.com/datasets/manideep1108/tusimple?resource=download

**Comment by lsj1012** [comment]
> 嗨，我不再使用 TuSimple，似乎该公司已禁用链接。请使用 Kaggle 链接下载数据集：https://www.kaggle.com/datasets/manideep1108/tusimple?resource=download

Thank you very much

**Comment by wy1663890176** [comment]
你好，你下载下来了吗，我注册不了账号 

> > 嗨，我不再使用 TuSimple，似乎该公司已禁用链接。请使用 Kaggle 链接下载数据集：https://www.kaggle.com/datasets/manideep1108/tusimple?resource=download
> 
> 谢谢

**Comment by wy1663890176** [comment]
> Hi @lsj1012 @wy1663890176 @02666 @SANGHEEMOON I am no longer with TuSimple and it seems that the company has disable the links. Please use the Kaggle link to download the dataset: https://www.kaggle.com/datasets/manideep1108/tusimple?resource=download

谢谢

**Comment by lsj1012** [comment]
> 你好，你下载下来了吗，我注册不了账号
> 
> > > 嗨，我不再使用 TuSimple，似乎该公司已禁用链接。请使用 Kaggle 链接下载数据集：https://www.kaggle.com/datasets/manideep1108/tusimple?resource=download
> > 
> > 
> > 谢谢

The download is complete

**Comment by wy1663890176** [comment]
> > 你好，你下载下来了吗，我注册不了账号
> > > > 嗨，我不再使用 TuSimple，似乎该公司已禁用链接。请使用 Kaggle 链接下载数据集：https://www.kaggle.com/datasets/manideep1108/tusimple?resource=download
> > > 
> > > 
> > > 谢谢
> 
> 下载完成

xiexie

**Comment by wy1663890176** [comment]
> 嗨，我不再使用 TuSimple，似乎该公司已禁用链接。请使用 Kaggle 链接下载数据集：https://www.kaggle.com/datasets/manideep1108/tusimple?resource=download

你好，想问一下，有生成的train_DRL_list.json和test_DRL_list.json这两个文件，我的环境运行会出错，生成的是空的，还有MyTuSimpleLane我文件夹里的所有文件都是空的

**Comment by 02666** [comment]
The file of test_DRL_list.json and train_DRL_list.json  is empty. How can I solve it
